# Test project: NUnitNetTests
# NuGet project: StateMachineNet
name: Publish package to GitHub
on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_PROJECT: NUnitNetTests
      LIB_PROJECT: StateMachineNet
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '7.0.111'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal $TEST_PROJECT

      - name: Pack
        run: dotnet pack --no-build -p:PatchNumber=$GITHUB_RUN_NUMBER --configuration Release $LIB_PROJECT/$LIB_PROJECT.csproj --output .

      - name: Push package to GitHub
        run: dotnet nuget push *.nupkg --skip-duplicate --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ secrets.PACKAGE_UPLOAD_SECRET }}